# Generated by Django 3.2.20 on 2023-10-19 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_sauce_name', models.CharField(max_length=300)),
                ('dessert_sauce_description', models.CharField(max_length=500)),
                ('dessert_sauce_type', models.CharField(choices=[('Cold Sauce', 'Cold Sauce'), ('Hot Sauce', 'Hot Sauce')], default='old Dessert_sauce', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_sauce_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dessert_sauce_name'],
            },
        ),
        migrations.CreateModel(
            name='DessertSauceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_sauce_Steps', models.CharField(max_length=500)),
                ('dessert_sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dessert_sauces.dessertsauce')),
            ],
        ),
        migrations.CreateModel(
            name='DessertSauceIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_sauce_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dessert_sauce_unit_type', models.CharField(choices=[('gr', 'gr'), ('Kg', 'Kg'), ('Oz', 'Oz'), ('lb', 'lSb'), ('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('floz', 'floz'), ('Pint', 'Pint'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50)),
                ('dessert_sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dessert_sauces.dessertsauce')),
                ('dessert_sauce_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_sauceing', to='products.product')),
            ],
        ),
    ]
