# Generated by Django 3.2.20 on 2024-01-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dessert_sauces', '0004_remove_dessertsauce_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessertsauce',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_sauce_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
