# Generated by Django 3.2.20 on 2024-01-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessert_sauces', '0005_dessertsauce_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessertsauceingredients',
            old_name='dessert_sauce_name',
            new_name='dessert_sauce',
        ),
        migrations.RenameField(
            model_name='dessertsaucemethod',
            old_name='dessert_sauce_name',
            new_name='dessert_sauce',
        ),
        migrations.RenameField(
            model_name='dessertsaucemethod',
            old_name='dessert_sauce_Steps',
            new_name='dessert_sauce_steps',
        ),
        migrations.AlterField(
            model_name='dessertsauce',
            name='dessert_sauce_type',
            field=models.CharField(choices=[('Cold Sauce', 'Cold Sauce'), ('Hot Sauce', 'Hot Sauce')], default='Cold Dessert_sauce', max_length=50),
        ),
    ]
