# Generated by Django 3.2.20 on 2024-01-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessert_sauces', '0008_auto_20240112_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessertsauceingredients',
            old_name='dessertsauce',
            new_name='dessert_sauce',
        ),
        migrations.RenameField(
            model_name='dessertsaucemethod',
            old_name='dessertsauce',
            new_name='dessert_sauce',
        ),
    ]
