# Generated by Django 3.2.20 on 2024-01-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_courses', '0002_auto_20240107_1655'),
        ('sauces', '0002_auto_20240107_1655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish_name', models.CharField(max_length=300)),
                ('main_dish_description', models.CharField(max_length=500)),
                ('main_dish_type', models.CharField(choices=[('cold_main', 'Cold Main'), ('hot_main', 'Hot Main')], default='Cold Main', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_dish_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['main_dish_name'],
            },
        ),
        migrations.CreateModel(
            name='MainDishSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_dishes.maindish')),
                ('main_dish_sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_sauce', to='sauces.sauce')),
            ],
        ),
        migrations.CreateModel(
            name='MainDishElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_dishes.maindish')),
                ('main_dish_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_element', to='main_courses.main')),
            ],
        ),
    ]
