# Generated by Django 3.2.20 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindish',
            name='main_dish_type',
            field=models.CharField(choices=[('Cold Main', 'Cold Main'), ('Hot Main', 'Hot Main')], default='Cold Main', max_length=50),
        ),
    ]
