# Generated by Django 3.2.20 on 2024-01-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sides', '0003_auto_20240107_1655'),
        ('main_dishes', '0002_alter_maindish_main_dish_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDishSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_dishes.maindish')),
                ('main_dish_side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_side', to='sides.side')),
            ],
        ),
    ]
