# Generated by Django 3.2.20 on 2024-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sauces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='sauce_course',
            field=models.CharField(choices=[('main', 'Main'), ('starter', 'Starter'), ('side', 'Side')], default='Side', max_length=50),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='sauce_type',
            field=models.CharField(choices=[('cold_sauce', 'Cold Sauce'), ('hot_sauce', 'Hot Sauce')], default='Cold Sauce', max_length=50),
        ),
        migrations.AlterField(
            model_name='sauceingredients',
            name='sauce_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauce_ing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='sauceingredients',
            name='sauce_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
    ]
