# Generated by Django 3.2.20 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0002_auto_20240107_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauce',
            name='sauce_course',
            field=models.CharField(choices=[('main', 'Main'), ('starter', 'Starter')], default='Side', max_length=50),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='sauce_type',
            field=models.CharField(choices=[('Cold Sauce', 'Cold Sauce'), ('Hot Sauce', 'Hot Sauce')], default='Cold Sauce', max_length=50),
        ),
    ]
