# Generated by Django 3.2.20 on 2023-10-14 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(max_length=300)),
                ('side_description', models.CharField(max_length=500)),
                ('side_type', models.CharField(choices=[('Cold Side', 'Cold Side'), ('Hot Side', 'Hot Side')], default='soup', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_recipe_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SideMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_Steps', models.CharField(max_length=500)),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sides.sides')),
            ],
        ),
        migrations.CreateModel(
            name='SideIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('side_unit_type', models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('oz', 'Oz'), ('lb', 'Lb'), ('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('floz', 'floz'), ('pint', 'Pint'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50)),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sides.sides')),
                ('side_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sideing', to='products.product')),
            ],
        ),
    ]
