# Generated by Django 3.2.20 on 2024-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sides', '0002_rename_sides_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideingredients',
            name='side_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_ing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='sideingredients',
            name='side_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
    ]
