# Generated by Django 3.2.20 on 2023-10-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_type',
            field=models.CharField(choices=[('Cold Dessert', 'Cold Dessert'), ('Hot Dessert', 'Hot Dessert'), ('Hot Sauce', 'Hot Sauce'), ('Cold Sauce', 'Cold Sauce')], default='soup', max_length=50),
        ),
    ]
