# Generated by Django 3.2.20 on 2023-10-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0003_alter_dessert_dessert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_type',
            field=models.CharField(choices=[('Cold Dessert', 'Cold Dessert'), ('Hot Dessert', 'Hot Dessert')], default='old Dessert', max_length=50),
        ),
    ]
