# Generated by Django 3.2.20 on 2024-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('desserts', '0004_alter_dessert_dessert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_type',
            field=models.CharField(choices=[('Cold Dessert', 'Cold Dessert'), ('Hot Dessert', 'Hot Dessert')], default='Cold Dessert', max_length=50),
        ),
        migrations.AlterField(
            model_name='dessertingredients',
            name='dessert_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_ing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='dessertingredients',
            name='dessert_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('Kg', 'Kg'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
    ]
