from django.urls import path
from .views import ViewDessertSauce, DessertSauceDelete
from . import views


urlpatterns = [
    path("",
         ViewDessertSauce.as_view(),
         name="dessert_sauces"
         ),
    path('dessert_sauces/add_dessert_sauce/',
         views.add_dessert_sauce,
         name='add_dessert_sauce'
         ),
    path('dessert_sauce_view/<pk>/',
         views.dessert_sauce_view,
         name='dessert_sauce_view'
         ),
    path('edit_dessert_sauce/<pk>/update/',
         views.edit_dessert_sauce,
         name="edit_dessert_sauce"
         ),
    path('dessert_sauce_delete/<pk>/delete/',
         DessertSauceDelete.as_view(),
         name="dessert_sauce_delete"
         ),
    path('dessert_sauce_method/<pk>/',
         views.dessert_sauce_method,
         name='dessert_sauce_method'
         ),
    path('dessert_sauce_ingredients/<pk>/',
         views.dessert_sauce_ingredients,
         name='dessert_sauce_ingredients'
         ),
    path('htmx/add_dessert_sauce_ing/',
         views.add_dessert_sauce_ing,
         name='add_dessert_sauce_ing'
         ),
    path('htmx/dessert_sauce_ing_details/<pk>/',
         views.dessert_sauce_ing_details,
         name="dessert_sauce_ing_details"
         ),
    path('dessert_sauce_ing_detail_view/<pk>/',
         views.dessert_sauce_ing_detail_view,
         name="dessert_sauce_ing_detail_view"
         ),
    path('dessert_sauce_step_detail_view/<pk>/',
         views.dessert_sauce_step_detail_view,
         name="dessert_sauce_stepdetail_view"
         ),
    path('htmx/update_dessert_sauce_ing/<pk>/update/',
         views.update_dessert_sauce_ing,
         name="update_dessert_sauce_ing"
         ),
    path('htmx/delete_ingredient/<pk>/delete/',
         views.delete_dessert_sauce_ing,
         name="delete_dessert_sauce_ing"
         ),
    path('htmx/add_dessert_sauce_step/',
         views.add_dessert_sauce_step,
         name='add_dessert_sauce_step'
         ),
    path('htmx/dessert_sauce_step_details/<pk>/update/',
         views.dessert_sauce_step_details,
         name="dessert_sauce_step_details"
         ),
    path('htmx/update_dessert_sauce_step/<pk>/update/',
         views.update_dessert_sauce_step,
         name="update_dessert_sauce_step"
         ),
    path('htmx/delete_dessert_sauce_step/<pk>/delete/',
         views.delete_dessert_sauce_step,
         name="delete_dessert_sauce_step"
         ),
]
