# Generated by Django 3.2.20 on 2023-09-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starteringredients',
            name='author',
        ),
        migrations.AddField(
            model_name='starteringredients',
            name='starter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='starters.starter'),
            preserve_default=False,
        ),
    ]
