# Generated by Django 3.2.20 on 2023-09-03 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('starters', '0002_auto_20230903_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='starteringredients',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='starteringredients',
            name='title',
        ),
        migrations.AddField(
            model_name='starter',
            name='starter_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starter',
            name='starter_meat_type',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('beef', 'Beef'), ('pork', 'Pork'), ('lamb', 'Lamb'), ('no_meat', 'No Meat')], default='chicken', max_length=50),
        ),
        migrations.AddField(
            model_name='starter',
            name='starter_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starter',
            name='starter_type',
            field=models.CharField(choices=[('soup', 'Soup'), ('cold_starter', 'Cold_Starter'), ('hot_starter', 'Hot Starter'), ('hot_sauce', 'Hot Sauce'), ('cold_sauce', 'Cold_Sauce')], default='soup', max_length=50),
        ),
        migrations.AddField(
            model_name='starter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_recipe_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='starteringredients',
            name='starter_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to='products.product'),
        ),
        migrations.AddField(
            model_name='starteringredients',
            name='starter_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starteringredients',
            name='starter_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('oz', 'Oz'), ('lb', 'Lb'), ('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('floz', 'floz'), ('pint', 'Pint'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
        migrations.CreateModel(
            name='StarterMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_Steps', models.CharField(max_length=500)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starters.starter')),
            ],
        ),
    ]
