# Generated by Django 3.2.20 on 2023-10-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('starters', '0003_auto_20230903_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starter',
            name='starter_meat_type',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('No Meat', 'No Meat')], default='chicken', max_length=50),
        ),
        migrations.AlterField(
            model_name='starter',
            name='starter_type',
            field=models.CharField(choices=[('Soup', 'Soup'), ('Cold Starter', 'Cold Starter'), ('Hot Starter', 'Hot Starter')], default='soup', max_length=50),
        ),
        migrations.AlterField(
            model_name='starteringredients',
            name='starter_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startering', to='products.product'),
        ),
    ]
