# Generated by Django 3.2.20 on 2024-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('starters', '0004_auto_20231011_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starteringredients',
            name='starter_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_ing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='starteringredients',
            name='starter_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
    ]
