# Generated by Django 3.2.20 on 2024-01-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dessert_sauces', '0002_auto_20240107_1655'),
        ('desserts', '0005_auto_20240107_1655'),
        ('dessert_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessertdishelement',
            name='dessert_dish_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_element', to='desserts.dessert'),
        ),
        migrations.AlterField(
            model_name='dessertdishsauce',
            name='dessert_dish_sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_sauce', to='dessert_sauces.dessertsauce'),
        ),
    ]
