# Generated by Django 3.2.20 on 2024-01-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessert_dishes', '0002_auto_20240107_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessertdish',
            name='user',
        ),
    ]
