# Generated by Django 3.2.20 on 2023-10-12 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=300)),
                ('main_description', models.CharField(max_length=500)),
                ('main_type', models.CharField(choices=[('cold_main', 'Cold_main'), ('hot_main', 'Hot main')], default='Cold_main', max_length=50)),
                ('main_meat_type', models.CharField(choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('No Meat', 'No Meat')], default='chicken', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['main_name'],
            },
        ),
        migrations.CreateModel(
            name='MainMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_Steps', models.CharField(max_length=500)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_courses.main')),
            ],
        ),
        migrations.CreateModel(
            name='MainIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_unit_type', models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('oz', 'Oz'), ('lb', 'Lb'), ('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('floz', 'floz'), ('pint', 'Pint'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_courses.main')),
                ('main_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maining', to='products.product')),
            ],
        ),
    ]
