# Generated by Django 3.2.20 on 2024-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('main_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='main_type',
            field=models.CharField(choices=[('cold_main', 'Cold_main'), ('hot_main', 'Hot main')], default='Cold Main', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainingredients',
            name='main_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='mainingredients',
            name='main_unit_type',
            field=models.CharField(choices=[('gr', 'gr'), ('kg', 'Kg'), ('ml', 'ml'), ('lt', 'lt')], default='gr', max_length=50),
        ),
    ]
