# Generated by Django 3.2.20 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_courses', '0002_auto_20240107_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='main_type',
            field=models.CharField(choices=[('Cold Main', 'Cold_main'), ('Hot Main', 'Hot main')], default='Cold Main', max_length=50),
        ),
    ]
