# Generated by Django 3.2.20 on 2024-01-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('starters', '0005_auto_20240107_1655'),
        ('sauces', '0002_auto_20240107_1655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_dish_name', models.CharField(max_length=300)),
                ('starter_dish_description', models.CharField(max_length=500)),
                ('starter_dish_type', models.CharField(choices=[('cold_starter', 'Cold Starter'), ('hot_starter', 'Hot Starter')], default='Cold starter', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_dish_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starter_dish_name'],
            },
        ),
        migrations.CreateModel(
            name='StarterDishSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starter_dishes.starterdish')),
                ('starter_dish_sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_sauce', to='sauces.sauce')),
            ],
        ),
        migrations.CreateModel(
            name='StarterDishElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starter_dishes.starterdish')),
                ('starter_dish_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_element', to='starters.starter')),
            ],
        ),
    ]
