# Generated by Django 3.2.20 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starterdish',
            name='starter_dish_type',
            field=models.CharField(choices=[('Cold Starter', 'Cold Starter'), ('Hot Starter', 'Hot Starter')], default='Cold starter', max_length=50),
        ),
    ]
