# Generated by Django 3.2.20 on 2024-01-09 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dessert_dishes', '0002_auto_20240107_1732'),
        ('main_dishes', '0002_alter_maindish_main_dish_type'),
        ('starter_dishes', '0002_alter_starterdish_starter_dish_type'),
        ('sides', '0003_auto_20240107_1655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('menu_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('menu_type', models.CharField(choices=[('à la carte', 'À la carte'), ('early bird', 'Early Bird'), ('specials', 'Specials')], default='Specials', max_length=25)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StarterDishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_price', models.FloatField(default=0.0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('starter_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_dish_item', to='starter_dishes.starterdish')),
            ],
            options={
                'ordering': ['starter_dish'],
            },
        ),
        migrations.CreateModel(
            name='SideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_price', models.FloatField(default=0.0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_item', to='sides.side')),
            ],
            options={
                'ordering': ['side'],
            },
        ),
        migrations.CreateModel(
            name='MainDishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_price', models.FloatField(default=0.0)),
                ('main_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_dish_item', to='main_dishes.maindish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
            options={
                'ordering': ['main_dish'],
            },
        ),
        migrations.CreateModel(
            name='DessertDishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_price', models.FloatField(default=0.0)),
                ('dessert_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dessert_dish_item', to='dessert_dishes.dessertdish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
            options={
                'ordering': ['dessert_dish'],
            },
        ),
        migrations.CreateModel(
            name='Allegens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegens', models.CharField(choices=[('gluten', 'Gluten'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('peanuts', 'Peanuts'), ('soya', 'Soya'), ('milk', 'Milk'), ('nuts', 'Nuts'), ('mustard', 'Mustard'), ('sesame', 'Sesame'), ('sulphites', 'Sulphites'), ('lupin', 'Lupin '), ('molluscs', 'Molluscs')], default='Gluten', max_length=25)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
    ]
