# Generated by Django 3.2.20 on 2024-01-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
