# Generated by Django 3.2.20 on 2024-01-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0003_auto_20240109_1323'),
        ('menu', '0002_auto_20240109_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='SauceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce_price', models.FloatField(default=0.0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauce_item', to='sauces.sauce')),
            ],
            options={
                'ordering': ['sauce'],
            },
        ),
    ]
