# Generated by Django 3.2.20 on 2024-01-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_sauceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allegens',
        ),
    ]
