# Generated by Django 3.2.20 on 2024-01-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_allegens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
    ]
