# Generated by Django 3.2.20 on 2023-09-02 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_type', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat'), ('fish', 'Fish'), ('dried', 'Dried'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('n/a', 'N/A')], default='Dairy', max_length=50)),
                ('product_freshness', models.CharField(choices=[('frozen', 'Frozen'), ('fresh', 'Fresh'), ('n/a', 'N/A')], default='Dried', max_length=50)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
